#!/bin/bash

watchexec --project-origin . -w processes \ 
aws s3 sync \
/Users/alan/workshop/minecraft-lua/processes/ \
s3://aws-minecraft-files/processes/ \
--profile Greenfield_Alan_Smith \
--size-only \
--exclude "*.DS_Store" \
--exclude ".git/*" \
