#!/bin/bash

watchexec --project-origin . \
-w ./ \
aws s3 sync \
/Users/alan/workshop/minecraft-lua/ \
s3://aws-minecraft-files/ \
--profile Greenfield_Alan_Smith \
--exclude "*.DS_Store" \
--exclude ".git/\*" \


