require "/_download"

download("/lib/_init.lua", "_init.lua")
download("/lib/_cut_chunk.lua", "_cut_chunk.lua")
download("/lib/_movement.lua", "_movement.lua")
download("/lib/_make_stairs.lua", "_make_stairs.lua")
download("/move/left.lua", "left.lua")
download("/move/right.lua", "right.lua")
download("/move/up.lua", "up.lua")
download("/move/down.lua", "down.lua")
download("/move/forward.lua", "forward.lua")
download("/move/back.lua", "back.lua")
download("/processes/harvest-trees/harvest-trees.lua", "harvest-trees.lua")
download("/processes/make-stairs/make-stairs.lua", "make-stairs.lua")
download("/processes/cut-chunk/cut-chunk.lua", "cut-chunk.lua")
download("/processes/name_turtle/name_turtle.lua", "name_turtle.lua")
download("/processes/cut_hall/cut_hall.lua", "cut_hall.lua")
